In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("anage_animalia.csv")
df

,HAGRID,Kingdom,Phylum,Class,Order,Family,Genus,Species,Common name,Female maturity (days),...,Source,Specimen origin,Sample size,Data quality,IMR (per yr),MRDT (yrs),Metabolic rate (W),Body mass (g),Temperature (K),References
0,32,Animalia,Chordata,Amphibia,Anura,Ascaphidae,Ascaphus,truei,Coastal tailed frog,NaN,...,525,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,"525,749"
1,33,Animalia,Chordata,Amphibia,Anura,Bombinatoridae,Bombina,bombina,Firebelly toad,1095.0,...,485,captivity,medium,acceptable,NaN,NaN,NaN,NaN,NaN,"485,525,749"
2,34,Animalia,Chordata,Amphibia,Anura,Bombinatoridae,Bombina,orientalis,Oriental firebelly toad,NaN,...,451,captivity,large,acceptable,NaN,NaN,NaN,NaN,NaN,"451,525,749"
3,35,Animalia,Chordata,Amphibia,Anura,Bombinatoridae,Bombina,variegata,Yellow-bellied toad,NaN,...,NaN,captivity,medium,acceptable,NaN,NaN,NaN,NaN,NaN,"24,525,749"
4,36,Animalia,Chordata,Amphibia,Anura,Bufonidae,Anaxyrus,americanus,American toad,910.0,...,525,captivity,medium,acceptable,NaN,NaN,0.00829,21.6,288.0,"37,268,426,525,749"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4508,4595,Animalia,Chordata,Teleostei,Zeiformes,Oreosomatidae,Allocyttus,niger,Black oreo,9855.0,...,454,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,454
4509,4596,Animalia,Chordata,Teleostei,Zeiformes,Oreosomatidae,Allocyttus,verrucosus,Warty oreo,NaN,...,22,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,"22,454"
4510,4597,Animalia,Chordata,Teleostei,Zeiformes,Oreosomatidae,Neocyttus,rhomboidalis,Spiky oreo,NaN,...,454,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,454
4511,4598,Animalia,Chordata,Teleostei,Zeiformes,Oreosomatidae,Pseudocyttus,maculatus,Smooth oreo,11315.0,...,454,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,454
4512,4599,Animalia,Chordata,Teleostei,Zeiformes,Zeidae,Zeus,faber,European john dory,1277.0,...,454,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,454

In [26]:
df.groupby("Class")["Species"].nunique().reset_index()

            Class  Species
0        Amphibia      177
1            Aves     1202
2  Chondrichthyes      115
3        Mammalia     1127
4        Reptilia      502
5       Teleostei      720

In [21]:
DTF = df.query("`Data quality` == 'high' or `Data quality` == 'acceptable'")
DTF

,HAGRID,Kingdom,Phylum,Class,Order,Family,Genus,Species,Common name,Female maturity (days),...,Source,Specimen origin,Sample size,Data quality,IMR (per yr),MRDT (yrs),Metabolic rate (W),Body mass (g),Temperature (K),References
0,32,Animalia,Chordata,Amphibia,Anura,Ascaphidae,Ascaphus,truei,Coastal tailed frog,NaN,...,525,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,"525,749"
1,33,Animalia,Chordata,Amphibia,Anura,Bombinatoridae,Bombina,bombina,Firebelly toad,1095.0,...,485,captivity,medium,acceptable,NaN,NaN,NaN,NaN,NaN,"485,525,749"
2,34,Animalia,Chordata,Amphibia,Anura,Bombinatoridae,Bombina,orientalis,Oriental firebelly toad,NaN,...,451,captivity,large,acceptable,NaN,NaN,NaN,NaN,NaN,"451,525,749"
3,35,Animalia,Chordata,Amphibia,Anura,Bombinatoridae,Bombina,variegata,Yellow-bellied toad,NaN,...,NaN,captivity,medium,acceptable,NaN,NaN,NaN,NaN,NaN,"24,525,749"
4,36,Animalia,Chordata,Amphibia,Anura,Bufonidae,Anaxyrus,americanus,American toad,910.0,...,525,captivity,medium,acceptable,NaN,NaN,0.00829,21.6,288.0,"37,268,426,525,749"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4508,4595,Animalia,Chordata,Teleostei,Zeiformes,Oreosomatidae,Allocyttus,niger,Black oreo,9855.0,...,454,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,454
4509,4596,Animalia,Chordata,Teleostei,Zeiformes,Oreosomatidae,Allocyttus,verrucosus,Warty oreo,NaN,...,22,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,"22,454"
4510,4597,Animalia,Chordata,Teleostei,Zeiformes,Oreosomatidae,Neocyttus,rhomboidalis,Spiky oreo,NaN,...,454,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,454
4511,4598,Animalia,Chordata,Teleostei,Zeiformes,Oreosomatidae,Pseudocyttus,maculatus,Smooth oreo,11315.0,...,454,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,454
4512,4599,Animalia,Chordata,Teleostei,Zeiformes,Zeidae,Zeus,faber,European john dory,1277.0,...,454,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,454

In [25]:
DTF["Maximum longevity (yrs)"].describe()

count    3924.000000
mean       18.952232
std        17.092274
min         0.160000
25%         9.000000
50%        15.000000
75%        24.000000
max       392.000000
Name: Maximum longevity (yrs), dtype: float64

In [ ]:
DTF.groupby("Class")

In [4]:
df.duplicated().sum()

np.int64(0)